title: Cicada
remote_theme: jekyll/minima
minima:
  skin: dark
description: >
  Cicada: A CLI chat interface for you and your friends.
header_pages:
  - about.md
  - docs.md
social_links:
- { platform: github, user_url: "https://github.com/prithvs/cicada" }
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

