title: Cicada
remote_theme: jekyll/minima
minima:
  skin: dark
description: >
  Cicada: A CLI chat interface for you and your friends.
header_pages:
  - about.md
social_links:
- { platform: github,         user_url: "https://github.com/prithvs/cicada" }
